version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # Maintain dependencies for PHP packages
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
